#!/usr/bin/env bash
# Shared credential helpers (sourced, not executed directly).

mw_is_auto_value() {
  local v="${1:-}"
  [[ -z "${v// }" ]] && return 0
  case "${v,,}" in
    changeme|mediawiki|mediawiki_root|auto|generate|default) return 0 ;;
  esac
  return 1
}

mw_random_token() {
  local len="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "$len"
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$len"
  fi
}

mw_random_db_identifier() {
  echo "${1}$(mw_random_token 8 | tr '[:upper:]' '[:lower:]')"
}

mw_ensure_secrets() {
  local secrets_file="${CONTAINER_ROOT:-/home/container}/.mw-secrets"
  local generated=0

  if [[ -f "$secrets_file" ]]; then
    # shellcheck disable=SC1090
    source "$secrets_file"
  fi

  if mw_is_auto_value "${DB_NAME:-}"; then
    if mw_is_auto_value "${DB_NAME_SAVED:-}"; then DB_NAME="$(mw_random_db_identifier mw_)"; generated=1
    else DB_NAME="${DB_NAME_SAVED}"; fi
  fi
  if mw_is_auto_value "${DB_USER:-}"; then
    if mw_is_auto_value "${DB_USER_SAVED:-}"; then DB_USER="$(mw_random_db_identifier mwu_)"; generated=1
    else DB_USER="${DB_USER_SAVED}"; fi
  fi
  if mw_is_auto_value "${DB_PASSWORD:-}"; then
    if mw_is_auto_value "${DB_PASSWORD_SAVED:-}"; then DB_PASSWORD="$(mw_random_token 24)"; generated=1
    else DB_PASSWORD="${DB_PASSWORD_SAVED}"; fi
  fi
  if mw_is_auto_value "${DB_ROOT_PASSWORD:-}"; then
    if mw_is_auto_value "${DB_ROOT_PASSWORD_SAVED:-}"; then DB_ROOT_PASSWORD="$(mw_random_token 24)"; generated=1
    else DB_ROOT_PASSWORD="${DB_ROOT_PASSWORD_SAVED}"; fi
  fi
  if mw_is_auto_value "${MW_ADMIN_PASS:-}"; then
    if mw_is_auto_value "${MW_ADMIN_PASS_SAVED:-}"; then MW_ADMIN_PASS="$(mw_random_token 20)"; generated=1
    else MW_ADMIN_PASS="${MW_ADMIN_PASS_SAVED}"; fi
  fi

  umask 077
  cat >"$secrets_file" <<EOF
# Auto-generated by MediaWiki egg — keep private
DB_NAME_SAVED='${DB_NAME}'
DB_USER_SAVED='${DB_USER}'
DB_PASSWORD_SAVED='${DB_PASSWORD}'
DB_ROOT_PASSWORD_SAVED='${DB_ROOT_PASSWORD}'
MW_ADMIN_PASS_SAVED='${MW_ADMIN_PASS}'
EOF
  chmod 600 "$secrets_file" 2>/dev/null || true
  export DB_NAME DB_USER DB_PASSWORD DB_ROOT_PASSWORD MW_ADMIN_PASS

  if [[ "$generated" -eq 1 ]]; then
    echo -e "\033[1;33m[Secrets] Credentials saved to .mw-secrets (see console once)${NC}"
    echo -e "  DB_NAME=${DB_NAME}"
    echo -e "  DB_USER=${DB_USER}"
    echo -e "  DB_PASSWORD=${DB_PASSWORD}"
    echo -e "  DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    echo -e "  MW_ADMIN_PASS=${MW_ADMIN_PASS}"
  fi
}
